name: SecureVault-Husna-Pipeline

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  # STAGE 1: SECRET DETECTION
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

  # STAGE 2: SAST (CodeQL v4)
  sast:
    runs-on: ubuntu-latest
    needs: secret-scan
    strategy:
      matrix:
        language: [python, javascript]
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v4
      - uses: github/codeql-action/analyze@v4

  # STAGE 3: CONTAINER SCAN (Member-1 ka Dockerfile use karega)
  container-scan:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: actions/checkout@v4
      # Ye command member-1 ki file path se uthayegi
      - name: Build SecureVault Image
        run: docker build -f ./docker/auth/Dockerfile -t securevault-auth:${{ github.sha }} .
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'securevault-auth:${{ github.sha }}'
          exit-code: '0'

  # STAGE 4: IaC SCAN
  iac-scan:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: k8s/
          framework: kubernetes

  # STAGE 5: DAST (SecureVault API Scan)
  dast:
    runs-on: ubuntu-latest
    needs: [container-scan, iac-scan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: ZAP Scan
        run: |
          docker run -t ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py \
            -t http://api-gateway:8080/openapi.json -f openapi

  # STAGE 6: DEPLOY (Aapka k8s folder use karega)
  deploy:
    runs-on: ubuntu-latest
    needs: dast
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy SecureVault K8s
        run: |
          kubectl apply -f k8s/auth-service/deployment.yaml
          kubectl apply -f k8s/namespaces/namespaces.yaml
